main.py
from flask import Flask
from routes.home import home_route
from routes.cliente import cliente_route

app = Flask(__name__)

app.register_blueprint(home_route)
app.register_blueprint(cliente_route, url_prefix='/clientes')


app.run(debug=True)

routes/cliente.py
from flask import Blueprint, render_template, request
from database.cliente import CLIENTES
cliente_route = Blueprint('cliente', __name__)

"""
Rota de clientes

    - /clientes/ (GET) - Listar os clientes
    - /clientes/ (POST) - inserir o cliente no servidor
    - /clientes/new (GET) - renderizar o formulário para criar um cliente
    - /clientes/<id> (GET) - obter os dados de um cliente
    - /clientes/<id>/edit (GET) - renderizar um formulário para editar um cliente
    - /cliente/<id>/update (PUT) - atualizar os dados do cliente
    - /clientes/<id>/delete (DELETE) - deleta o registro do usuario

"""


@cliente_route.route('/')
def lista_clientes():
    # listar os clientes
    return render_template('lista_clientes.html', clientes=CLIENTES)

@cliente_route.route('/', methods=['POST'])
def inserir_cliente():
    # inserir os dados do cliente

    data = request.json
    novo_usuario = {
        "id":len(CLIENTES) + 1,
        "nome": data['nome'],
        "email": data['email'],
    }
    CLIENTES.append(novo_usuario)

    return render_template('item_cliente.html', cliente=novo_usuario)

@cliente_route.route('/new')
def form_cliente():
    # formulário para cadastrar um cliente
    return render_template('form_cliente.html')

@cliente_route.route('/<int:cliente_id>')
def detalhe_cliente(cliente_id):
    # exibir detalhes do cliente
    return render_template('detalhe_cliente.html')

@cliente_route.route('/<int:cliente_id>/edit')
def form_edit_cliente(cliente_id):
    # formulário para editar um cliente
    return render_template('form_edit_cliente.html')

@cliente_route.route('/<int:cliente_id>/update', methods=['PUT'])
def atualizar_cliente(cliente_id):
    # atualizar informações do cliente

    pass

@cliente_route.route('/<int:cliente_id>/delete', methods=['DELETE'])
def deletar_cliente(cliente_id):
    # deletar um cliente
    global CLIENTES
    CLIENTES = [
        c for c in CLIENTES if c['id'] != cliente_id
    ]

    return {'deleted': 'ok'}

routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home():
    return render_template('index.html')

templates/form_cliente.html
<form class="c-form" action="{{ url_for('cliente.inserir_cliente') }}" method="POST" c-append="#lista-clientes">

    <div class="mb-3">
      <label class="form-label">Nome</label>
      <input type="text" class="form-control" name="nome">
    </div>

    <div class="mb-3">
        <label class="form-label">Email</label>
        <input type="text" class="form-control" name="email">
    </div>



    
    <button type="submit" class="btn btn-primary">Adicionar cliente</button>
</form>

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='app.css') }}">
  </head>
  <body>
    
    <div class="container">
      <h1 class="text-center">gestão de clientes</h1>

      <hr>
      <!-- formulario add clientes -->
      <div c-container="{{ url_for('cliente.form_cliente') }}"></div>

      <h2>Lista de clientes</h2>
      <!-- lista de clientes -->
      <div c-container="{{ url_for('cliente.lista_clientes') }}"></div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='cru.js') }}"></script>
  </body>
</html>

templates/item_cliente.html
<tr>
    <th scope="row">{{ cliente.id }}</th>
    <td>{{ cliente.nome }}</td>
    <td>{{ cliente.email }}</td>
    <td>
        <button class="btn btn-success">Editar</button>
        <button class="btn btn-danger" c-delete="{{ url_for('cliente.deletar_cliente', cliente_id=cliente.id) }}" c-remove-closest="tr">Deletar       
        </button>
    </td>
</tr>

templates/lista_clientes.html
<table class="table">
    <link rel="stylesheet" href="{{ url_for('static', filename='app.css') }}">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Email</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody id="lista-clientes">

        {% for cliente in clientes %}
            {% include 'item_cliente.html' %}
        {% endfor %}
      </tr>
    </tbody>
  </table>